module.exports = {
    TODO_ADD: 'TODO_ADD',
    TODO_TOGGLE: 'TODO_TOGGLE',
    TODO_REMOVE: 'TODO_REMOVE',
    TODOS_GET: 'TODOS_GET',
    TODOS_GETBYID: 'TODOS_GETBYID',
    TODOS_GETBYGROUPID: 'TODOS_GETBYGROUPID',
    ADDCOMMENT: 'ADDCOMMENT'
};
