'use strict';
module.exports = {
   BLERPBYID:'BLERPBYID',
   GETCOMMENTS:'GETCOMMENTS',
   ADDCOMMENT:'ADDCOMMENT',
   BLERPTAGS:'BLERPTAGS',
   BLERPLOCATIONS:'BLERPLOCATIONS',
   BLEERPSHAREDFEEDS:'BLEERPSHAREDFEEDS',
   TODO_TOGGLE:"TODO_TOGGLE"
};
